package com.growdata.emprendimiento.persistence.entidad;
// Generated 11/07/2019 04:10:46 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos implements java.io.Serializable {

    private BigDecimal idalumno;
    private Beneficiario beneficiario;
    private Funcionario funcionario;
    private Programacion programacion;
    private Date fecharegistro;
    private Set<Aprobacion> aprobacions = new HashSet<Aprobacion>(0);
    private Set<Seguimientoasistencia> seguimientoasistencias = new HashSet<Seguimientoasistencia>(0);

    public Alumnos() {
    }

    public Alumnos(BigDecimal idalumno) {
        this.idalumno = idalumno;
    }

    public Alumnos(BigDecimal idalumno, Beneficiario beneficiario, Funcionario funcionario, Programacion programacion, Date fecharegistro) {
        this.idalumno = idalumno;
        this.beneficiario = beneficiario;
        this.funcionario = funcionario;
        this.programacion = programacion;
        this.fecharegistro = fecharegistro;
    }

    public Alumnos(BigDecimal idalumno, Beneficiario beneficiario, Funcionario funcionario, Programacion programacion, Date fecharegistro, Set<Aprobacion> aprobacions, Set<Seguimientoasistencia> seguimientoasistencias) {
        this.idalumno = idalumno;
        this.beneficiario = beneficiario;
        this.funcionario = funcionario;
        this.programacion = programacion;
        this.fecharegistro = fecharegistro;
        this.aprobacions = aprobacions;
        this.seguimientoasistencias = seguimientoasistencias;
    }

    public BigDecimal getIdalumno() {
        return this.idalumno;
    }

    public void setIdalumno(BigDecimal idalumno) {
        this.idalumno = idalumno;
    }

    public Beneficiario getBeneficiario() {
        return this.beneficiario;
    }

    public void setBeneficiario(Beneficiario beneficiario) {
        this.beneficiario = beneficiario;
    }

    public Funcionario getFuncionario() {
        return this.funcionario;
    }

    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

    public Programacion getProgramacion() {
        return this.programacion;
    }

    public void setProgramacion(Programacion programacion) {
        this.programacion = programacion;
    }

    public Date getFecharegistro() {
        return this.fecharegistro;
    }

    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    public Set<Aprobacion> getAprobacions() {
        return this.aprobacions;
    }

    public void setAprobacions(Set<Aprobacion> aprobacions) {
        this.aprobacions = aprobacions;
    }

    public Set<Seguimientoasistencia> getSeguimientoasistencias() {
        return this.seguimientoasistencias;
    }

    public void setSeguimientoasistencias(Set<Seguimientoasistencia> seguimientoasistencias) {
        this.seguimientoasistencias = seguimientoasistencias;
    }

}
