package com.growdata.emprendimiento.persistence.entidad;
// Generated 11/07/2019 04:10:46 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Aprobacion generated by hbm2java
 */
public class Aprobacion implements java.io.Serializable {

    private BigDecimal idaprobacion;
    private Funcionario funcionario;
    private Alumnos alumnos;
    private short porcentajeaprobacionobtenido;
    private short calificacionfinal;
    private Date fecharegistro;
    private short calificacionfuncionario;

    public Aprobacion() {
    }

    public Aprobacion(BigDecimal idaprobacion, Funcionario funcionario, Alumnos alumnos, short porcentajeaprobacionobtenido, short calificacionfinal, short calificacionfuncionario, Date fecharegistro) {
        this.idaprobacion = idaprobacion;
        this.funcionario = funcionario;
        this.alumnos = alumnos;
        this.porcentajeaprobacionobtenido = porcentajeaprobacionobtenido;
        this.calificacionfinal = calificacionfinal;
        this.calificacionfuncionario = calificacionfuncionario;
        this.fecharegistro = fecharegistro;
    }

    public BigDecimal getIdaprobacion() {
        return this.idaprobacion;
    }

    public void setIdaprobacion(BigDecimal idaprobacion) {
        this.idaprobacion = idaprobacion;
    }

    public Funcionario getFuncionario() {
        return this.funcionario;
    }

    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

    public Alumnos getAlumnos() {
        return this.alumnos;
    }

    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }

    public short getPorcentajeaprobacionobtenido() {
        return this.porcentajeaprobacionobtenido;
    }

    public void setPorcentajeaprobacionobtenido(short porcentajeaprobacionobtenido) {
        this.porcentajeaprobacionobtenido = porcentajeaprobacionobtenido;
    }

    public short getCalificacionfinal() {
        return this.calificacionfinal;
    }

    public void setCalificacionfinal(short calificacionfinal) {
        this.calificacionfinal = calificacionfinal;
    }

    public Date getFecharegistro() {
        return this.fecharegistro;
    }

    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    public short getCalificacionfuncionario() {
        return calificacionfuncionario;
    }

    public void setCalificacionfuncionario(short calificacionfuncionario) {
        this.calificacionfuncionario = calificacionfuncionario;
    }

}
