package com.growdata.emprendimiento.persistence.entidad;
// Generated 11/07/2019 04:10:46 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cajacompensacion generated by hbm2java
 */
public class Cajacompensacion implements java.io.Serializable {

    private BigDecimal idcajacompensacion;
    private Estadocajacompensacion estadocajacompensacion;
    private String nombrecajacompensacion;
    private Date fecharegistro;
    private String codigoccf;
    private String departamento;
    private Set<Temasevaluacion> temasevaluacions = new HashSet<Temasevaluacion>(0);
    private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);
    private Set<Comiteevaluacion> comiteevaluacions = new HashSet<Comiteevaluacion>(0);
    private Set<Emprendimiento> emprendimientos = new HashSet<Emprendimiento>(0);
    private Set<Preguntas> preguntases = new HashSet<Preguntas>(0);

    public Cajacompensacion() {
    }

    public Cajacompensacion(BigDecimal idcajacompensacion, Estadocajacompensacion estadocajacompensacion) {
        this.idcajacompensacion = idcajacompensacion;
        this.estadocajacompensacion = estadocajacompensacion;
    }

    public Cajacompensacion(BigDecimal idcajacompensacion, Estadocajacompensacion estadocajacompensacion, String nombrecajacompensacion, Date fecharegistro, String codigoccf, String departamento) {
        this.idcajacompensacion = idcajacompensacion;
        this.estadocajacompensacion = estadocajacompensacion;
        this.nombrecajacompensacion = nombrecajacompensacion;
        this.fecharegistro = fecharegistro;
        this.codigoccf = codigoccf;
        this.departamento = departamento;
    }

    public Cajacompensacion(BigDecimal idcajacompensacion, Estadocajacompensacion estadocajacompensacion, String nombrecajacompensacion, Date fecharegistro, String codigoccf, String departamento, Set<Funcionario> funcionarios) {
        this.idcajacompensacion = idcajacompensacion;
        this.estadocajacompensacion = estadocajacompensacion;
        this.nombrecajacompensacion = nombrecajacompensacion;
        this.fecharegistro = fecharegistro;
        this.codigoccf = codigoccf;
        this.departamento = departamento;
        this.funcionarios = funcionarios;
    }

    public BigDecimal getIdcajacompensacion() {
        return this.idcajacompensacion;
    }

    public void setIdcajacompensacion(BigDecimal idcajacompensacion) {
        this.idcajacompensacion = idcajacompensacion;
    }

    public Estadocajacompensacion getEstadocajacompensacion() {
        return this.estadocajacompensacion;
    }

    public void setEstadocajacompensacion(Estadocajacompensacion estadocajacompensacion) {
        this.estadocajacompensacion = estadocajacompensacion;
    }

    public String getNombrecajacompensacion() {
        return this.nombrecajacompensacion;
    }

    public void setNombrecajacompensacion(String nombrecajacompensacion) {
        this.nombrecajacompensacion = nombrecajacompensacion;
    }

    public Date getFecharegistro() {
        return this.fecharegistro;
    }

    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    public String getCodigoccf() {
        return this.codigoccf;
    }

    public void setCodigoccf(String codigoccf) {
        this.codigoccf = codigoccf;
    }

    public String getDepartamento() {
        return this.departamento;
    }

    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    public Set<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }

    public void setFuncionarios(Set<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }

    public Set<Temasevaluacion> getTemasevaluacions() {
        return temasevaluacions;
    }

    public void setTemasevaluacions(Set<Temasevaluacion> temasevaluacions) {
        this.temasevaluacions = temasevaluacions;
    }

    public Set<Comiteevaluacion> getComiteevaluacions() {
        return comiteevaluacions;
    }

    public void setComiteevaluacions(Set<Comiteevaluacion> comiteevaluacions) {
        this.comiteevaluacions = comiteevaluacions;
    }

    public Set<Emprendimiento> getEmprendimientos() {
        return emprendimientos;
    }

    public void setEmprendimientos(Set<Emprendimiento> emprendimientos) {
        this.emprendimientos = emprendimientos;
    }

    public Set<Preguntas> getPreguntases() {
        return preguntases;
    }

    public void setPreguntases(Set<Preguntas> preguntases) {
        this.preguntases = preguntases;
    }

}
