package com.growdata.emprendimiento.persistence.entidad;
// Generated 11/07/2019 04:10:46 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Capacitacionprograma generated by hbm2java
 */
public class Capacitacionprograma implements java.io.Serializable {

    private long idcapacitacionprograma;
    private Categoria categoria;
    private Estadocapacitacionprograma estadocapacitacionprograma;
    private long idoferenteinstitucion;
    private String nombrecapacitacionprograma;
    private Date fecharegistro;
    private Set<Programacion> programacions = new HashSet<Programacion>(0);
    private Set<Modulociclo> modulociclos = new HashSet<Modulociclo>(0);

    public Capacitacionprograma() {
    }

    public Capacitacionprograma(long idcapacitacionprograma) {
        this.idcapacitacionprograma = idcapacitacionprograma;
    }

    public Capacitacionprograma(long idcapacitacionprograma, Categoria categoria, Estadocapacitacionprograma estadocapacitacionprograma, long idoferenteinstitucion, String nombrecapacitacionprograma, Date fecharegistro) {
        this.idcapacitacionprograma = idcapacitacionprograma;
        this.categoria = categoria;
        this.estadocapacitacionprograma = estadocapacitacionprograma;
        this.idoferenteinstitucion = idoferenteinstitucion;
        this.nombrecapacitacionprograma = nombrecapacitacionprograma;
        this.fecharegistro = fecharegistro;
    }

    public Capacitacionprograma(long idcapacitacionprograma, Categoria categoria, Estadocapacitacionprograma estadocapacitacionprograma, long idoferenteinstitucion, String nombrecapacitacionprograma, Date fecharegistro, Set<Programacion> programacions, Set<Modulociclo> modulociclos) {
        this.idcapacitacionprograma = idcapacitacionprograma;
        this.categoria = categoria;
        this.estadocapacitacionprograma = estadocapacitacionprograma;
        this.idoferenteinstitucion = idoferenteinstitucion;
        this.nombrecapacitacionprograma = nombrecapacitacionprograma;
        this.fecharegistro = fecharegistro;
        this.programacions = programacions;
        this.modulociclos = modulociclos;
    }

    public long getIdcapacitacionprograma() {
        return this.idcapacitacionprograma;
    }

    public void setIdcapacitacionprograma(long idcapacitacionprograma) {
        this.idcapacitacionprograma = idcapacitacionprograma;
    }

    public Categoria getCategoria() {
        return this.categoria;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    public Estadocapacitacionprograma getEstadocapacitacionprograma() {
        return this.estadocapacitacionprograma;
    }

    public void setEstadocapacitacionprograma(Estadocapacitacionprograma estadocapacitacionprograma) {
        this.estadocapacitacionprograma = estadocapacitacionprograma;
    }

    public long getIdoferenteinstitucion() {
        return this.idoferenteinstitucion;
    }

    public void setIdoferenteinstitucion(long idoferenteinstitucion) {
        this.idoferenteinstitucion = idoferenteinstitucion;
    }

    public String getNombrecapacitacionprograma() {
        return this.nombrecapacitacionprograma;
    }

    public void setNombrecapacitacionprograma(String nombrecapacitacionprograma) {
        this.nombrecapacitacionprograma = nombrecapacitacionprograma;
    }

    public Date getFecharegistro() {
        return this.fecharegistro;
    }

    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    public Set<Programacion> getProgramacions() {
        return this.programacions;
    }

    public void setProgramacions(Set<Programacion> programacions) {
        this.programacions = programacions;
    }

    public Set<Modulociclo> getModulociclos() {
        return this.modulociclos;
    }

    public void setModulociclos(Set<Modulociclo> modulociclos) {
        this.modulociclos = modulociclos;
    }

}
