package com.growdata.emprendimiento.persistence.entidad;
// Generated 11/07/2019 04:10:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {


     private long idcategoria;
     private String nombrecategoria;
     private String descripcion;
     private short porcentajeaprobacion;
     private short calificacionaprobacion;
     private Set<Capacitacionprograma> capacitacionprogramas = new HashSet<Capacitacionprograma>(0);

    public Categoria() {
    }

	
    public Categoria(long idcategoria, String nombrecategoria, String descripcion, short porcentajeaprobacion, short calificacionaprobacion) {
        this.idcategoria = idcategoria;
        this.nombrecategoria = nombrecategoria;
        this.descripcion = descripcion;
        this.porcentajeaprobacion = porcentajeaprobacion;
        this.calificacionaprobacion = calificacionaprobacion;
    }
    public Categoria(long idcategoria, String nombrecategoria, String descripcion, short porcentajeaprobacion, short calificacionaprobacion, Set<Capacitacionprograma> capacitacionprogramas) {
       this.idcategoria = idcategoria;
       this.nombrecategoria = nombrecategoria;
       this.descripcion = descripcion;
       this.porcentajeaprobacion = porcentajeaprobacion;
       this.calificacionaprobacion = calificacionaprobacion;
       this.capacitacionprogramas = capacitacionprogramas;
    }
   
    public long getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(long idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getNombrecategoria() {
        return this.nombrecategoria;
    }
    
    public void setNombrecategoria(String nombrecategoria) {
        this.nombrecategoria = nombrecategoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public short getPorcentajeaprobacion() {
        return this.porcentajeaprobacion;
    }
    
    public void setPorcentajeaprobacion(short porcentajeaprobacion) {
        this.porcentajeaprobacion = porcentajeaprobacion;
    }
    public short getCalificacionaprobacion() {
        return this.calificacionaprobacion;
    }
    
    public void setCalificacionaprobacion(short calificacionaprobacion) {
        this.calificacionaprobacion = calificacionaprobacion;
    }
    public Set<Capacitacionprograma> getCapacitacionprogramas() {
        return this.capacitacionprogramas;
    }
    
    public void setCapacitacionprogramas(Set<Capacitacionprograma> capacitacionprogramas) {
        this.capacitacionprogramas = capacitacionprogramas;
    }




}


