package com.growdata.emprendimiento.persistence.entidad;
// Generated 11/07/2019 04:10:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Estadofuncionario generated by hbm2java
 */
public class Estadofuncionario implements java.io.Serializable {


     private BigDecimal idestadofuncionario;
     private String nombreestado;
     private String descripcion;
     private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);

    public Estadofuncionario() {
    }

	
    public Estadofuncionario(BigDecimal idestadofuncionario, String nombreestado, String descripcion) {
        this.idestadofuncionario = idestadofuncionario;
        this.nombreestado = nombreestado;
        this.descripcion = descripcion;
    }
    public Estadofuncionario(BigDecimal idestadofuncionario, String nombreestado, String descripcion, Set<Funcionario> funcionarios) {
       this.idestadofuncionario = idestadofuncionario;
       this.nombreestado = nombreestado;
       this.descripcion = descripcion;
       this.funcionarios = funcionarios;
    }
   
    public BigDecimal getIdestadofuncionario() {
        return this.idestadofuncionario;
    }
    
    public void setIdestadofuncionario(BigDecimal idestadofuncionario) {
        this.idestadofuncionario = idestadofuncionario;
    }
    public String getNombreestado() {
        return this.nombreestado;
    }
    
    public void setNombreestado(String nombreestado) {
        this.nombreestado = nombreestado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }




}


