package com.growdata.emprendimiento.persistence.entidad;
// Generated 11/07/2019 04:10:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estadocapacitacionprograma generated by hbm2java
 */
public class Estadocapacitacionprograma implements java.io.Serializable {


     private long idestadocapacitacionprograma;
     private String nombreestadocapacitacionprog;
     private String descripcion;
     private Set<Capacitacionprograma> capacitacionprogramas = new HashSet<Capacitacionprograma>(0);

    public Estadocapacitacionprograma() {
    }

	
    public Estadocapacitacionprograma(long idestadocapacitacionprograma, String nombreestadocapacitacionprog, String descripcion) {
        this.idestadocapacitacionprograma = idestadocapacitacionprograma;
        this.nombreestadocapacitacionprog = nombreestadocapacitacionprog;
        this.descripcion = descripcion;
    }
    public Estadocapacitacionprograma(long idestadocapacitacionprograma, String nombreestadocapacitacionprog, String descripcion, Set<Capacitacionprograma> capacitacionprogramas) {
       this.idestadocapacitacionprograma = idestadocapacitacionprograma;
       this.nombreestadocapacitacionprog = nombreestadocapacitacionprog;
       this.descripcion = descripcion;
       this.capacitacionprogramas = capacitacionprogramas;
    }
   
    public long getIdestadocapacitacionprograma() {
        return this.idestadocapacitacionprograma;
    }
    
    public void setIdestadocapacitacionprograma(long idestadocapacitacionprograma) {
        this.idestadocapacitacionprograma = idestadocapacitacionprograma;
    }
    public String getNombreestadocapacitacionprog() {
        return this.nombreestadocapacitacionprog;
    }
    
    public void setNombreestadocapacitacionprog(String nombreestadocapacitacionprog) {
        this.nombreestadocapacitacionprog = nombreestadocapacitacionprog;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Capacitacionprograma> getCapacitacionprogramas() {
        return this.capacitacionprogramas;
    }
    
    public void setCapacitacionprogramas(Set<Capacitacionprograma> capacitacionprogramas) {
        this.capacitacionprogramas = capacitacionprogramas;
    }




}


