package com.growdata.emprendimiento.persistence.entidad;
// Generated 11/07/2019 04:10:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estadodocente generated by hbm2java
 */
public class Estadodocente implements java.io.Serializable {


     private long idestadodocente;
     private String nombreestadodocente;
     private String descripcion;
     private Set<Docentes> docenteses = new HashSet<Docentes>(0);

    public Estadodocente() {
    }

	
    public Estadodocente(long idestadodocente, String nombreestadodocente, String descripcion) {
        this.idestadodocente = idestadodocente;
        this.nombreestadodocente = nombreestadodocente;
        this.descripcion = descripcion;
    }
    public Estadodocente(long idestadodocente, String nombreestadodocente, String descripcion, Set<Docentes> docenteses) {
       this.idestadodocente = idestadodocente;
       this.nombreestadodocente = nombreestadodocente;
       this.descripcion = descripcion;
       this.docenteses = docenteses;
    }
   
    public long getIdestadodocente() {
        return this.idestadodocente;
    }
    
    public void setIdestadodocente(long idestadodocente) {
        this.idestadodocente = idestadodocente;
    }
    public String getNombreestadodocente() {
        return this.nombreestadodocente;
    }
    
    public void setNombreestadodocente(String nombreestadodocente) {
        this.nombreestadodocente = nombreestadodocente;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Docentes> getDocenteses() {
        return this.docenteses;
    }
    
    public void setDocenteses(Set<Docentes> docenteses) {
        this.docenteses = docenteses;
    }




}


