package com.growdata.emprendimiento.persistence.entidad;
// Generated 11/07/2019 04:10:46 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Estadocajacompensacion generated by hbm2java
 */
public class Estadocajacompensacion implements java.io.Serializable {

    private BigDecimal idestadocajacompensacion;
    private String nombreestadocaja;
    private String descripcion;
    private Set<Cajacompensacion> cajacompensacions = new HashSet<Cajacompensacion>(0);

    public Estadocajacompensacion() {
    }

    public Estadocajacompensacion(BigDecimal idestadocajacompensacion) {
        this.idestadocajacompensacion = idestadocajacompensacion;
    }

    public Estadocajacompensacion(BigDecimal idestadocajacompensacion, String nombreestadocaja, String descripcion) {
        this.idestadocajacompensacion = idestadocajacompensacion;
        this.nombreestadocaja = nombreestadocaja;
        this.descripcion = descripcion;
    }

    public Estadocajacompensacion(BigDecimal idestadocajacompensacion, String nombreestadocaja, String descripcion, Set<Cajacompensacion> cajacompensacions) {
        this.idestadocajacompensacion = idestadocajacompensacion;
        this.nombreestadocaja = nombreestadocaja;
        this.descripcion = descripcion;
        this.cajacompensacions = cajacompensacions;
    }

    public BigDecimal getIdestadocajacompensacion() {
        return this.idestadocajacompensacion;
    }

    public void setIdestadocajacompensacion(BigDecimal idestadocajacompensacion) {
        this.idestadocajacompensacion = idestadocajacompensacion;
    }

    public String getNombreestadocaja() {
        return this.nombreestadocaja;
    }

    public void setNombreestadocaja(String nombreestadocaja) {
        this.nombreestadocaja = nombreestadocaja;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set<Cajacompensacion> getCajacompensacions() {
        return this.cajacompensacions;
    }

    public void setCajacompensacions(Set<Cajacompensacion> cajacompensacions) {
        this.cajacompensacions = cajacompensacions;
    }

}
