package com.growdata.emprendimiento.persistence.entidad;
// Generated 11/07/2019 04:10:46 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Modulociclo generated by hbm2java
 */
public class Modulociclo implements java.io.Serializable {

    private long idmodulociclo;
    private Capacitacionprograma capacitacionprograma;
    private String nombremodulociclo;
    private short intensidadhoraria;
    private Date fecharegistro;
    private Set<Seguimientoasistencia> seguimientoasistencias = new HashSet<Seguimientoasistencia>(0);

    public Modulociclo() {
    }

    public Modulociclo(long idmodulociclo) {
        this.idmodulociclo = idmodulociclo;
    }

    public Modulociclo(long idmodulociclo, Capacitacionprograma capacitacionprograma, String nombremodulociclo, short intensidadhoraria, Date fecharegistro) {
        this.idmodulociclo = idmodulociclo;
        this.capacitacionprograma = capacitacionprograma;
        this.nombremodulociclo = nombremodulociclo;
        this.intensidadhoraria = intensidadhoraria;
        this.fecharegistro = fecharegistro;
    }

    public Modulociclo(long idmodulociclo, Capacitacionprograma capacitacionprograma, String nombremodulociclo, short intensidadhoraria, Date fecharegistro, Set<Seguimientoasistencia> seguimientoasistencias) {
        this.idmodulociclo = idmodulociclo;
        this.capacitacionprograma = capacitacionprograma;
        this.nombremodulociclo = nombremodulociclo;
        this.intensidadhoraria = intensidadhoraria;
        this.fecharegistro = fecharegistro;
        this.seguimientoasistencias = seguimientoasistencias;
    }

    public long getIdmodulociclo() {
        return this.idmodulociclo;
    }

    public void setIdmodulociclo(long idmodulociclo) {
        this.idmodulociclo = idmodulociclo;
    }

    public Capacitacionprograma getCapacitacionprograma() {
        return this.capacitacionprograma;
    }

    public void setCapacitacionprograma(Capacitacionprograma capacitacionprograma) {
        this.capacitacionprograma = capacitacionprograma;
    }

    public String getNombremodulociclo() {
        return this.nombremodulociclo;
    }

    public void setNombremodulociclo(String nombremodulociclo) {
        this.nombremodulociclo = nombremodulociclo;
    }

    public short getIntensidadhoraria() {
        return this.intensidadhoraria;
    }

    public void setIntensidadhoraria(short intensidadhoraria) {
        this.intensidadhoraria = intensidadhoraria;
    }

    public Date getFecharegistro() {
        return this.fecharegistro;
    }

    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    public Set<Seguimientoasistencia> getSeguimientoasistencias() {
        return this.seguimientoasistencias;
    }

    public void setSeguimientoasistencias(Set<Seguimientoasistencia> seguimientoasistencias) {
        this.seguimientoasistencias = seguimientoasistencias;
    }

}
