package com.growdata.emprendimiento.persistence.entidad;
// Generated 11/07/2019 04:10:46 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Programacion generated by hbm2java
 */
public class Programacion implements java.io.Serializable {

    private BigDecimal idprogramacion;
    private Funcionario funcionario;
    private Estadosesion estadosesion;
    private Capacitacionprograma capacitacionprograma;
    private Docentes docentes;
    private BigDecimal idInstitucion;
    private Timestamp fechainicioprogramacion;
    private Timestamp fechafinalrogramacion;
    private short maxasistentes;
    private Date fecharegistro;
    private String ubicacion;
    private Set<Alumnos> alumnoses = new HashSet<Alumnos>(0);

    public Programacion() {
    }

    public Programacion(BigDecimal idprogramacion) {
        this.idprogramacion = idprogramacion;
    }

    public Programacion(BigDecimal idprogramacion, Estadosesion estadosesion, Funcionario funcionario, Capacitacionprograma capacitacionprograma, Docentes docentes, BigDecimal idInstitucion, Timestamp fechainicioprogramacion, Timestamp fechafinalrogramacion, short maxasistentes, Date fecharegistro, String ubicacion) {
        this.idprogramacion = idprogramacion;
        this.estadosesion = estadosesion;
        this.funcionario = funcionario;
        this.capacitacionprograma = capacitacionprograma;
        this.docentes = docentes;
        this.idInstitucion = idInstitucion;
        this.fechainicioprogramacion = fechainicioprogramacion;
        this.fechafinalrogramacion = fechafinalrogramacion;
        this.maxasistentes = maxasistentes;
        this.fecharegistro = fecharegistro;
        this.ubicacion = ubicacion;
    }

    public Programacion(BigDecimal idprogramacion, Estadosesion estadosesion, Funcionario funcionario, Capacitacionprograma capacitacionprograma, Docentes docentes, BigDecimal idInstitucion, Timestamp fechainicioprogramacion, Timestamp fechafinalrogramacion, short maxasistentes, Date fecharegistro, String ubicacion, Set<Alumnos> alumnoses) {
        this.idprogramacion = idprogramacion;
        this.estadosesion = estadosesion;
        this.funcionario = funcionario;
        this.capacitacionprograma = capacitacionprograma;
        this.docentes = docentes;
        this.idInstitucion = idInstitucion;
        this.fechainicioprogramacion = fechainicioprogramacion;
        this.fechafinalrogramacion = fechafinalrogramacion;
        this.maxasistentes = maxasistentes;
        this.fecharegistro = fecharegistro;
        this.alumnoses = alumnoses;
        this.ubicacion = ubicacion;
    }

    public BigDecimal getIdprogramacion() {
        return this.idprogramacion;
    }

    public void setIdprogramacion(BigDecimal idprogramacion) {
        this.idprogramacion = idprogramacion;
    }

    public Funcionario getFuncionario() {
        return this.funcionario;
    }

    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

    public Capacitacionprograma getCapacitacionprograma() {
        return this.capacitacionprograma;
    }

    public void setCapacitacionprograma(Capacitacionprograma capacitacionprograma) {
        this.capacitacionprograma = capacitacionprograma;
    }

    public Docentes getDocentes() {
        return this.docentes;
    }

    public void setDocentes(Docentes docentes) {
        this.docentes = docentes;
    }

    public BigDecimal getIdInstitucion() {
        return idInstitucion;
    }

    public void setIdInstitucion(BigDecimal idInstitucion) {
        this.idInstitucion = idInstitucion;
    }

    public Timestamp getFechainicioprogramacion() {
        return this.fechainicioprogramacion;
    }

    public void setFechainicioprogramacion(Timestamp fechainicioprogramacion) {
        this.fechainicioprogramacion = fechainicioprogramacion;
    }

    public Timestamp getFechafinalrogramacion() {
        return this.fechafinalrogramacion;
    }

    public void setFechafinalrogramacion(Timestamp fechafinalrogramacion) {
        this.fechafinalrogramacion = fechafinalrogramacion;
    }

    public short getMaxasistentes() {
        return this.maxasistentes;
    }

    public void setMaxasistentes(short maxasistentes) {
        this.maxasistentes = maxasistentes;
    }

    public Date getFecharegistro() {
        return this.fecharegistro;
    }

    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    public Set<Alumnos> getAlumnoses() {
        return this.alumnoses;
    }

    public void setAlumnoses(Set<Alumnos> alumnoses) {
        this.alumnoses = alumnoses;
    }

    public Estadosesion getEstadosesion() {
        return estadosesion;
    }

    public void setEstadosesion(Estadosesion estadosesion) {
        this.estadosesion = estadosesion;
    }

    public String getUbicacion() {
        return ubicacion;
    }

    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

}
