package com.growdata.emprendimiento.persistence.entidad;
// Generated 11/07/2019 04:10:46 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tipodocumentoid generated by hbm2java
 */
public class Tipodocumentoid implements java.io.Serializable {

    private BigDecimal idtipodocumento;
    private String nombredocumento;
    private String descripcion;
    private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);
    private Set<Docentes> docenteses = new HashSet<Docentes>(0);
    private Set<Beneficiario> beneficiarios = new HashSet<Beneficiario>(0);

    public Tipodocumentoid() {
    }

    public Tipodocumentoid(BigDecimal idtipodocumento) {
        this.idtipodocumento = idtipodocumento;
    }

    public Tipodocumentoid(BigDecimal idtipodocumento, String nombredocumento, String descripcion) {
        this.idtipodocumento = idtipodocumento;
        this.nombredocumento = nombredocumento;
        this.descripcion = descripcion;
    }

    public Tipodocumentoid(BigDecimal idtipodocumento, String nombredocumento, String descripcion, Set<Funcionario> funcionarios, Set<Docentes> docenteses, Set<Beneficiario> beneficiarios) {
        this.idtipodocumento = idtipodocumento;
        this.nombredocumento = nombredocumento;
        this.descripcion = descripcion;
        this.funcionarios = funcionarios;
        this.docenteses = docenteses;
        this.beneficiarios = beneficiarios;
    }

    public BigDecimal getIdtipodocumento() {
        return this.idtipodocumento;
    }

    public void setIdtipodocumento(BigDecimal idtipodocumento) {
        this.idtipodocumento = idtipodocumento;
    }

    public String getNombredocumento() {
        return this.nombredocumento;
    }

    public void setNombredocumento(String nombredocumento) {
        this.nombredocumento = nombredocumento;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }

    public void setFuncionarios(Set<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }

    public Set<Docentes> getDocenteses() {
        return this.docenteses;
    }

    public void setDocenteses(Set<Docentes> docenteses) {
        this.docenteses = docenteses;
    }

    public Set<Beneficiario> getBeneficiarios() {
        return this.beneficiarios;
    }

    public void setBeneficiarios(Set<Beneficiario> beneficiarios) {
        this.beneficiarios = beneficiarios;
    }

}
