package com.growdata.emprendimiento.persistence.entidadSIMPC;
// Generated 20/06/2019 03:04:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Abonos generated by hbm2java
 */
public class Abonos implements java.io.Serializable {


     private BigDecimal idabono;
     private Recobros recobros;
     private BigDecimal cargaid;
     private Timestamp fecha;
     private int valorabono;
     private Long saldodeuda;
     private BigDecimal linea;
     private int idusuario;

    public Abonos() {
    }

	
    public Abonos(BigDecimal idabono, Recobros recobros, BigDecimal cargaid, Timestamp fecha, int valorabono, int idusuario) {
        this.idabono = idabono;
        this.recobros = recobros;
        this.cargaid = cargaid;
        this.fecha = fecha;
        this.valorabono = valorabono;
        this.idusuario = idusuario;
    }
    public Abonos(BigDecimal idabono, Recobros recobros, BigDecimal cargaid, Timestamp fecha, int valorabono, Long saldodeuda, BigDecimal linea, int idusuario) {
       this.idabono = idabono;
       this.recobros = recobros;
       this.cargaid = cargaid;
       this.fecha = fecha;
       this.valorabono = valorabono;
       this.saldodeuda = saldodeuda;
       this.linea = linea;
       this.idusuario = idusuario;
    }
   
    public BigDecimal getIdabono() {
        return this.idabono;
    }
    
    public void setIdabono(BigDecimal idabono) {
        this.idabono = idabono;
    }
    public Recobros getRecobros() {
        return this.recobros;
    }
    
    public void setRecobros(Recobros recobros) {
        this.recobros = recobros;
    }
    public BigDecimal getCargaid() {
        return this.cargaid;
    }
    
    public void setCargaid(BigDecimal cargaid) {
        this.cargaid = cargaid;
    }
    public Timestamp getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Timestamp fecha) {
        this.fecha = fecha;
    }
    public int getValorabono() {
        return this.valorabono;
    }
    
    public void setValorabono(int valorabono) {
        this.valorabono = valorabono;
    }
    public Long getSaldodeuda() {
        return this.saldodeuda;
    }
    
    public void setSaldodeuda(Long saldodeuda) {
        this.saldodeuda = saldodeuda;
    }
    public BigDecimal getLinea() {
        return this.linea;
    }
    
    public void setLinea(BigDecimal linea) {
        this.linea = linea;
    }
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }




}


