package com.growdata.emprendimiento.persistence.entidadSIMPC;
// Generated 18/07/2019 02:40:02 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos implements java.io.Serializable {

    private BigDecimal id;
    private String divipola;
    private String nombre;
    private Set<Sedes> sedeses = new HashSet<Sedes>(0);
    private Set<Municipios> municipioses = new HashSet<Municipios>(0);

    public Departamentos() {
    }

    public Departamentos(BigDecimal id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public Departamentos(BigDecimal id, String divipola, String nombre, Set<Sedes> sedeses, Set<Municipios> municipioses) {
        this.id = id;
        this.divipola = divipola;
        this.nombre = nombre;
        this.sedeses = sedeses;
        this.municipioses = municipioses;
    }

    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    public String getDivipola() {
        return this.divipola;
    }

    public void setDivipola(String divipola) {
        this.divipola = divipola;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set<Sedes> getSedeses() {
        return this.sedeses;
    }

    public void setSedeses(Set<Sedes> sedeses) {
        this.sedeses = sedeses;
    }

    public Set<Municipios> getMunicipioses() {
        return this.municipioses;
    }

    public void setMunicipioses(Set<Municipios> municipioses) {
        this.municipioses = municipioses;
    }

}
