package com.growdata.emprendimiento.persistence.entidadSIMPC;
// Generated 20/06/2019 03:04:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Emprendedor generated by hbm2java
 */
public class Emprendedor implements java.io.Serializable {

    private BigDecimal idEmprendedor;
    private MdFDatosBasicos mdFDatosBasicos;
    private char esEmprendedor;
    private Timestamp fechaRegistroEmprendedor;

    public Emprendedor() {
    }
    
    public Emprendedor(MdFDatosBasicos mdFDatosBasicos, Character esEmprendedor, Timestamp fechaRegistroEmprendedor) {
        this.mdFDatosBasicos = mdFDatosBasicos;
        this.esEmprendedor = esEmprendedor;
        this.fechaRegistroEmprendedor = fechaRegistroEmprendedor;
    }

    public Emprendedor(BigDecimal idEmprendedor, MdFDatosBasicos mdFDatosBasicos, char esEmprendedor, Timestamp fechaRegistroEmprendedor) {
        this.idEmprendedor = idEmprendedor;
        this.mdFDatosBasicos = mdFDatosBasicos;
        this.esEmprendedor = esEmprendedor;
        this.fechaRegistroEmprendedor = fechaRegistroEmprendedor;
    }

    public BigDecimal getIdEmprendedor() {
        return this.idEmprendedor;
    }

    public void setIdEmprendedor(BigDecimal idEmprendedor) {
        this.idEmprendedor = idEmprendedor;
    }

    public MdFDatosBasicos getMdFDatosBasicos() {
        return this.mdFDatosBasicos;
    }

    public void setMdFDatosBasicos(MdFDatosBasicos mdFDatosBasicos) {
        this.mdFDatosBasicos = mdFDatosBasicos;
    }

    public char getEsEmprendedor() {
        return this.esEmprendedor;
    }

    public void setEsEmprendedor(char esEmprendedor) {
        this.esEmprendedor = esEmprendedor;
    }

    public Timestamp getFechaRegistroEmprendedor() {
        return this.fechaRegistroEmprendedor;
    }

    public void setFechaRegistroEmprendedor(Timestamp fechaRegistroEmprendedor) {
        this.fechaRegistroEmprendedor = fechaRegistroEmprendedor;
    }

}
