package com.growdata.emprendimiento.persistence.entidadSIMPC;
// Generated 20/06/2019 03:04:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Timestamp;
import java.util.Date;

/**
 * Instituciones generated by hbm2java
 */
public class Instituciones implements java.io.Serializable {

    private BigDecimal id;
    private Timestamp fechaAprobacion;
    private String correoElectronico;
    private String numeroTelefono;
    private Timestamp fechaCreacion;
    private Long digitoVerificacion;
    private String nombreInstitucion;
    private int naturalezaJuridica;
    private Timestamp fechaModificacion;
    private String nit;
    private char origen;
    private Blob certificacionCalidad;
    private Date vencimientoCertificacion;
    private char estado;
    private BigDecimal idUsuarioCreacion;
    private BigDecimal tipoDocumento;
    private BigDecimal idUsuarioModificacion;
    private BigDecimal tipoInstitucionId;
    private char estadoAprobacion;
    private BigDecimal tipoCertificacion;

    public Instituciones() {
    }

    public Instituciones(BigDecimal id, String correoElectronico, Timestamp fechaCreacion, String nombreInstitucion, int naturalezaJuridica, String nit, char origen, char estado, BigDecimal idUsuarioCreacion, BigDecimal tipoDocumento, BigDecimal tipoInstitucionId, char estadoAprobacion, BigDecimal tipoCertificacion) {
        this.id = id;
        this.correoElectronico = correoElectronico;
        this.fechaCreacion = fechaCreacion;
        this.nombreInstitucion = nombreInstitucion;
        this.naturalezaJuridica = naturalezaJuridica;
        this.nit = nit;
        this.origen = origen;
        this.estado = estado;
        this.idUsuarioCreacion = idUsuarioCreacion;
        this.tipoDocumento = tipoDocumento;
        this.tipoInstitucionId = tipoInstitucionId;
        this.estadoAprobacion = estadoAprobacion;
        this.tipoCertificacion = tipoCertificacion;
    }

    public Instituciones(BigDecimal id, Timestamp fechaAprobacion, String correoElectronico, String numeroTelefono, Timestamp fechaCreacion, Long digitoVerificacion, String nombreInstitucion, int naturalezaJuridica, Timestamp fechaModificacion, String nit, char origen, Blob certificacionCalidad, Date vencimientoCertificacion, char estado, BigDecimal idUsuarioCreacion, BigDecimal tipoDocumento, BigDecimal idUsuarioModificacion, BigDecimal tipoInstitucionId, char estadoAprobacion, BigDecimal tipoCertificacion) {
        this.id = id;
        this.fechaAprobacion = fechaAprobacion;
        this.correoElectronico = correoElectronico;
        this.numeroTelefono = numeroTelefono;
        this.fechaCreacion = fechaCreacion;
        this.digitoVerificacion = digitoVerificacion;
        this.nombreInstitucion = nombreInstitucion;
        this.naturalezaJuridica = naturalezaJuridica;
        this.fechaModificacion = fechaModificacion;
        this.nit = nit;
        this.origen = origen;
        this.certificacionCalidad = certificacionCalidad;
        this.vencimientoCertificacion = vencimientoCertificacion;
        this.estado = estado;
        this.idUsuarioCreacion = idUsuarioCreacion;
        this.tipoDocumento = tipoDocumento;
        this.idUsuarioModificacion = idUsuarioModificacion;
        this.tipoInstitucionId = tipoInstitucionId;
        this.estadoAprobacion = estadoAprobacion;
        this.tipoCertificacion = tipoCertificacion;
    }

    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    public Timestamp getFechaAprobacion() {
        return this.fechaAprobacion;
    }

    public void setFechaAprobacion(Timestamp fechaAprobacion) {
        this.fechaAprobacion = fechaAprobacion;
    }

    public String getCorreoElectronico() {
        return this.correoElectronico;
    }

    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }

    public String getNumeroTelefono() {
        return this.numeroTelefono;
    }

    public void setNumeroTelefono(String numeroTelefono) {
        this.numeroTelefono = numeroTelefono;
    }

    public Timestamp getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Timestamp fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Long getDigitoVerificacion() {
        return this.digitoVerificacion;
    }

    public void setDigitoVerificacion(Long digitoVerificacion) {
        this.digitoVerificacion = digitoVerificacion;
    }

    public String getNombreInstitucion() {
        return this.nombreInstitucion;
    }

    public void setNombreInstitucion(String nombreInstitucion) {
        this.nombreInstitucion = nombreInstitucion;
    }

    public int getNaturalezaJuridica() {
        return this.naturalezaJuridica;
    }

    public void setNaturalezaJuridica(int naturalezaJuridica) {
        this.naturalezaJuridica = naturalezaJuridica;
    }

    public Timestamp getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Timestamp fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    public String getNit() {
        return this.nit;
    }

    public void setNit(String nit) {
        this.nit = nit;
    }

    public char getOrigen() {
        return this.origen;
    }

    public void setOrigen(char origen) {
        this.origen = origen;
    }

    public Blob getCertificacionCalidad() {
        return this.certificacionCalidad;
    }

    public void setCertificacionCalidad(Blob certificacionCalidad) {
        this.certificacionCalidad = certificacionCalidad;
    }

    public Date getVencimientoCertificacion() {
        return this.vencimientoCertificacion;
    }

    public void setVencimientoCertificacion(Date vencimientoCertificacion) {
        this.vencimientoCertificacion = vencimientoCertificacion;
    }

    public char getEstado() {
        return this.estado;
    }

    public void setEstado(char estado) {
        this.estado = estado;
    }

    public BigDecimal getIdUsuarioCreacion() {
        return this.idUsuarioCreacion;
    }

    public void setIdUsuarioCreacion(BigDecimal idUsuarioCreacion) {
        this.idUsuarioCreacion = idUsuarioCreacion;
    }

    public BigDecimal getTipoDocumento() {
        return this.tipoDocumento;
    }

    public void setTipoDocumento(BigDecimal tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    public BigDecimal getIdUsuarioModificacion() {
        return this.idUsuarioModificacion;
    }

    public void setIdUsuarioModificacion(BigDecimal idUsuarioModificacion) {
        this.idUsuarioModificacion = idUsuarioModificacion;
    }

    public BigDecimal getTipoInstitucionId() {
        return this.tipoInstitucionId;
    }

    public void setTipoInstitucionId(BigDecimal tipoInstitucionId) {
        this.tipoInstitucionId = tipoInstitucionId;
    }

    public char getEstadoAprobacion() {
        return this.estadoAprobacion;
    }

    public void setEstadoAprobacion(char estadoAprobacion) {
        this.estadoAprobacion = estadoAprobacion;
    }

    public BigDecimal getTipoCertificacion() {
        return this.tipoCertificacion;
    }

    public void setTipoCertificacion(BigDecimal tipoCertificacion) {
        this.tipoCertificacion = tipoCertificacion;
    }

}
