package com.growdata.emprendimiento.persistence.entidadSIMPC;
// Generated 20/06/2019 03:04:05 PM by Hibernate Tools 4.3.1

/**
 * MdFFosfecId generated by hbm2java
 */
public class MdFFosfecId implements java.io.Serializable {

    private String tipoIdentificacion;
    private String numeroIdentificacion;

    public MdFFosfecId() {
    }

    public MdFFosfecId(String tipoIdentificacion, String numeroIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
        this.numeroIdentificacion = numeroIdentificacion;
    }

    public String getTipoIdentificacion() {
        return this.tipoIdentificacion;
    }

    public void setTipoIdentificacion(String tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }

    public String getNumeroIdentificacion() {
        return this.numeroIdentificacion;
    }

    public void setNumeroIdentificacion(String numeroIdentificacion) {
        this.numeroIdentificacion = numeroIdentificacion;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof MdFFosfecId)) {
            return false;
        }
        MdFFosfecId castOther = (MdFFosfecId) other;

        return ((this.getTipoIdentificacion() == castOther.getTipoIdentificacion()) || (this.getTipoIdentificacion() != null && castOther.getTipoIdentificacion() != null && this.getTipoIdentificacion().equals(castOther.getTipoIdentificacion())))
                && ((this.getNumeroIdentificacion() == castOther.getNumeroIdentificacion()) || (this.getNumeroIdentificacion() != null && castOther.getNumeroIdentificacion() != null && this.getNumeroIdentificacion().equals(castOther.getNumeroIdentificacion())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getTipoIdentificacion() == null ? 0 : this.getTipoIdentificacion().hashCode());
        result = 37 * result + (getNumeroIdentificacion() == null ? 0 : this.getNumeroIdentificacion().hashCode());
        return result;
    }

}
