package com.growdata.emprendimiento.persistence.entidadSIMPC;
// Generated 20/06/2019 03:04:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * MdFFosfec generated by hbm2java
 */
public class MdFFosfec implements java.io.Serializable {

    private MdFFosfecId id;
    private BigDecimal cargaId;
    private BigDecimal linea;
    private String tipoNovedad;
    private String codigoCcf;
    private String primerNombre;
    private String segundoNombre;
    private String primerApellido;
    private String segundoApellido;
    private Date fechaNacimiento;
    private String genero;
    private String departamentoResidencia;
    private String ciudadResidencia;
    private String rangoSalarial;
    private String inscripcionServicioEmpleo;
    private String tipoVinculacionCcf;
    private String ultimaCcf;
    private Date fechaPostulacionMpc;
    private String administradoraSalud;
    private String postulaPension;
    private String administradoraPension;
    private String subsidioCuotaMonetaria;
    private String ahorroCesantiasMpc;
    private String administradoraFondoCesantias;
    private String porcentajeAhorroCesantias;
    private String postulaBonoAlimentacion;
    private String verificacionRequisitos;
    private Date fechaVerificacionPostu;
    private String beneficiarioDelMecanismo;
    private String cumpleRutaDeEmpleabildad;
    private Date fechaLiquidacionBeneficio;
    private String periodoBeneficioLiquidado;
    private String numeroBeneficiosLiquidados;
    private String numeroCuotasLiquidadas;
    private String numeroPersonasCargo;
    private String numeroCuotasIncentivo;
    private String numeroBonosLiquidados;
    private String montoLiquidadoSalud;
    private String montoLiquidadoPension;
    private String montoLiquidadoCuota;
    private String montoLiquidadoCesantias;
    private String montoLiquidadoAlimentacion;
    private String valorTotalPrestaciones;
    private String renunciaVoluntaria;
    private Date fechaRenuncia;
    private String perdidaBeneficio;
    private Date fechaPerdidaBeneficio;
    private String terminacionBeneficio;
    private Date fechaTerminacionBeneficio;

    public MdFFosfec() {
    }

    public MdFFosfec(MdFFosfecId id, BigDecimal cargaId, BigDecimal linea) {
        this.id = id;
        this.cargaId = cargaId;
        this.linea = linea;
    }

    public MdFFosfec(MdFFosfecId id, BigDecimal cargaId, BigDecimal linea, String tipoNovedad, String codigoCcf, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, Date fechaNacimiento, String genero, String departamentoResidencia, String ciudadResidencia, String rangoSalarial, String inscripcionServicioEmpleo, String tipoVinculacionCcf, String ultimaCcf, Date fechaPostulacionMpc, String administradoraSalud, String postulaPension, String administradoraPension, String subsidioCuotaMonetaria, String ahorroCesantiasMpc, String administradoraFondoCesantias, String porcentajeAhorroCesantias, String postulaBonoAlimentacion, String verificacionRequisitos, Date fechaVerificacionPostu, String beneficiarioDelMecanismo, String cumpleRutaDeEmpleabildad, Date fechaLiquidacionBeneficio, String periodoBeneficioLiquidado, String numeroBeneficiosLiquidados, String numeroCuotasLiquidadas, String numeroPersonasCargo, String numeroCuotasIncentivo, String numeroBonosLiquidados, String montoLiquidadoSalud, String montoLiquidadoPension, String montoLiquidadoCuota, String montoLiquidadoCesantias, String montoLiquidadoAlimentacion, String valorTotalPrestaciones, String renunciaVoluntaria, Date fechaRenuncia, String perdidaBeneficio, Date fechaPerdidaBeneficio, String terminacionBeneficio, Date fechaTerminacionBeneficio) {
        this.id = id;
        this.cargaId = cargaId;
        this.linea = linea;
        this.tipoNovedad = tipoNovedad;
        this.codigoCcf = codigoCcf;
        this.primerNombre = primerNombre;
        this.segundoNombre = segundoNombre;
        this.primerApellido = primerApellido;
        this.segundoApellido = segundoApellido;
        this.fechaNacimiento = fechaNacimiento;
        this.genero = genero;
        this.departamentoResidencia = departamentoResidencia;
        this.ciudadResidencia = ciudadResidencia;
        this.rangoSalarial = rangoSalarial;
        this.inscripcionServicioEmpleo = inscripcionServicioEmpleo;
        this.tipoVinculacionCcf = tipoVinculacionCcf;
        this.ultimaCcf = ultimaCcf;
        this.fechaPostulacionMpc = fechaPostulacionMpc;
        this.administradoraSalud = administradoraSalud;
        this.postulaPension = postulaPension;
        this.administradoraPension = administradoraPension;
        this.subsidioCuotaMonetaria = subsidioCuotaMonetaria;
        this.ahorroCesantiasMpc = ahorroCesantiasMpc;
        this.administradoraFondoCesantias = administradoraFondoCesantias;
        this.porcentajeAhorroCesantias = porcentajeAhorroCesantias;
        this.postulaBonoAlimentacion = postulaBonoAlimentacion;
        this.verificacionRequisitos = verificacionRequisitos;
        this.fechaVerificacionPostu = fechaVerificacionPostu;
        this.beneficiarioDelMecanismo = beneficiarioDelMecanismo;
        this.cumpleRutaDeEmpleabildad = cumpleRutaDeEmpleabildad;
        this.fechaLiquidacionBeneficio = fechaLiquidacionBeneficio;
        this.periodoBeneficioLiquidado = periodoBeneficioLiquidado;
        this.numeroBeneficiosLiquidados = numeroBeneficiosLiquidados;
        this.numeroCuotasLiquidadas = numeroCuotasLiquidadas;
        this.numeroPersonasCargo = numeroPersonasCargo;
        this.numeroCuotasIncentivo = numeroCuotasIncentivo;
        this.numeroBonosLiquidados = numeroBonosLiquidados;
        this.montoLiquidadoSalud = montoLiquidadoSalud;
        this.montoLiquidadoPension = montoLiquidadoPension;
        this.montoLiquidadoCuota = montoLiquidadoCuota;
        this.montoLiquidadoCesantias = montoLiquidadoCesantias;
        this.montoLiquidadoAlimentacion = montoLiquidadoAlimentacion;
        this.valorTotalPrestaciones = valorTotalPrestaciones;
        this.renunciaVoluntaria = renunciaVoluntaria;
        this.fechaRenuncia = fechaRenuncia;
        this.perdidaBeneficio = perdidaBeneficio;
        this.fechaPerdidaBeneficio = fechaPerdidaBeneficio;
        this.terminacionBeneficio = terminacionBeneficio;
        this.fechaTerminacionBeneficio = fechaTerminacionBeneficio;
    }

    public MdFFosfecId getId() {
        return this.id;
    }

    public void setId(MdFFosfecId id) {
        this.id = id;
    }

    public BigDecimal getCargaId() {
        return this.cargaId;
    }

    public void setCargaId(BigDecimal cargaId) {
        this.cargaId = cargaId;
    }

    public BigDecimal getLinea() {
        return this.linea;
    }

    public void setLinea(BigDecimal linea) {
        this.linea = linea;
    }

    public String getTipoNovedad() {
        return this.tipoNovedad;
    }

    public void setTipoNovedad(String tipoNovedad) {
        this.tipoNovedad = tipoNovedad;
    }

    public String getCodigoCcf() {
        return this.codigoCcf;
    }

    public void setCodigoCcf(String codigoCcf) {
        this.codigoCcf = codigoCcf;
    }

    public String getPrimerNombre() {
        return this.primerNombre;
    }

    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }

    public String getSegundoNombre() {
        return this.segundoNombre;
    }

    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }

    public String getPrimerApellido() {
        return this.primerApellido;
    }

    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }

    public String getSegundoApellido() {
        return this.segundoApellido;
    }

    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }

    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getGenero() {
        return this.genero;
    }

    public void setGenero(String genero) {
        this.genero = genero;
    }

    public String getDepartamentoResidencia() {
        return this.departamentoResidencia;
    }

    public void setDepartamentoResidencia(String departamentoResidencia) {
        this.departamentoResidencia = departamentoResidencia;
    }

    public String getCiudadResidencia() {
        return this.ciudadResidencia;
    }

    public void setCiudadResidencia(String ciudadResidencia) {
        this.ciudadResidencia = ciudadResidencia;
    }

    public String getRangoSalarial() {
        return this.rangoSalarial;
    }

    public void setRangoSalarial(String rangoSalarial) {
        this.rangoSalarial = rangoSalarial;
    }

    public String getInscripcionServicioEmpleo() {
        return this.inscripcionServicioEmpleo;
    }

    public void setInscripcionServicioEmpleo(String inscripcionServicioEmpleo) {
        this.inscripcionServicioEmpleo = inscripcionServicioEmpleo;
    }

    public String getTipoVinculacionCcf() {
        return this.tipoVinculacionCcf;
    }

    public void setTipoVinculacionCcf(String tipoVinculacionCcf) {
        this.tipoVinculacionCcf = tipoVinculacionCcf;
    }

    public String getUltimaCcf() {
        return this.ultimaCcf;
    }

    public void setUltimaCcf(String ultimaCcf) {
        this.ultimaCcf = ultimaCcf;
    }

    public Date getFechaPostulacionMpc() {
        return this.fechaPostulacionMpc;
    }

    public void setFechaPostulacionMpc(Date fechaPostulacionMpc) {
        this.fechaPostulacionMpc = fechaPostulacionMpc;
    }

    public String getAdministradoraSalud() {
        return this.administradoraSalud;
    }

    public void setAdministradoraSalud(String administradoraSalud) {
        this.administradoraSalud = administradoraSalud;
    }

    public String getPostulaPension() {
        return this.postulaPension;
    }

    public void setPostulaPension(String postulaPension) {
        this.postulaPension = postulaPension;
    }

    public String getAdministradoraPension() {
        return this.administradoraPension;
    }

    public void setAdministradoraPension(String administradoraPension) {
        this.administradoraPension = administradoraPension;
    }

    public String getSubsidioCuotaMonetaria() {
        return this.subsidioCuotaMonetaria;
    }

    public void setSubsidioCuotaMonetaria(String subsidioCuotaMonetaria) {
        this.subsidioCuotaMonetaria = subsidioCuotaMonetaria;
    }

    public String getAhorroCesantiasMpc() {
        return this.ahorroCesantiasMpc;
    }

    public void setAhorroCesantiasMpc(String ahorroCesantiasMpc) {
        this.ahorroCesantiasMpc = ahorroCesantiasMpc;
    }

    public String getAdministradoraFondoCesantias() {
        return this.administradoraFondoCesantias;
    }

    public void setAdministradoraFondoCesantias(String administradoraFondoCesantias) {
        this.administradoraFondoCesantias = administradoraFondoCesantias;
    }

    public String getPorcentajeAhorroCesantias() {
        return this.porcentajeAhorroCesantias;
    }

    public void setPorcentajeAhorroCesantias(String porcentajeAhorroCesantias) {
        this.porcentajeAhorroCesantias = porcentajeAhorroCesantias;
    }

    public String getPostulaBonoAlimentacion() {
        return this.postulaBonoAlimentacion;
    }

    public void setPostulaBonoAlimentacion(String postulaBonoAlimentacion) {
        this.postulaBonoAlimentacion = postulaBonoAlimentacion;
    }

    public String getVerificacionRequisitos() {
        return this.verificacionRequisitos;
    }

    public void setVerificacionRequisitos(String verificacionRequisitos) {
        this.verificacionRequisitos = verificacionRequisitos;
    }

    public Date getFechaVerificacionPostu() {
        return this.fechaVerificacionPostu;
    }

    public void setFechaVerificacionPostu(Date fechaVerificacionPostu) {
        this.fechaVerificacionPostu = fechaVerificacionPostu;
    }

    public String getBeneficiarioDelMecanismo() {
        return this.beneficiarioDelMecanismo;
    }

    public void setBeneficiarioDelMecanismo(String beneficiarioDelMecanismo) {
        this.beneficiarioDelMecanismo = beneficiarioDelMecanismo;
    }

    public String getCumpleRutaDeEmpleabildad() {
        return this.cumpleRutaDeEmpleabildad;
    }

    public void setCumpleRutaDeEmpleabildad(String cumpleRutaDeEmpleabildad) {
        this.cumpleRutaDeEmpleabildad = cumpleRutaDeEmpleabildad;
    }

    public Date getFechaLiquidacionBeneficio() {
        return this.fechaLiquidacionBeneficio;
    }

    public void setFechaLiquidacionBeneficio(Date fechaLiquidacionBeneficio) {
        this.fechaLiquidacionBeneficio = fechaLiquidacionBeneficio;
    }

    public String getPeriodoBeneficioLiquidado() {
        return this.periodoBeneficioLiquidado;
    }

    public void setPeriodoBeneficioLiquidado(String periodoBeneficioLiquidado) {
        this.periodoBeneficioLiquidado = periodoBeneficioLiquidado;
    }

    public String getNumeroBeneficiosLiquidados() {
        return this.numeroBeneficiosLiquidados;
    }

    public void setNumeroBeneficiosLiquidados(String numeroBeneficiosLiquidados) {
        this.numeroBeneficiosLiquidados = numeroBeneficiosLiquidados;
    }

    public String getNumeroCuotasLiquidadas() {
        return this.numeroCuotasLiquidadas;
    }

    public void setNumeroCuotasLiquidadas(String numeroCuotasLiquidadas) {
        this.numeroCuotasLiquidadas = numeroCuotasLiquidadas;
    }

    public String getNumeroPersonasCargo() {
        return this.numeroPersonasCargo;
    }

    public void setNumeroPersonasCargo(String numeroPersonasCargo) {
        this.numeroPersonasCargo = numeroPersonasCargo;
    }

    public String getNumeroCuotasIncentivo() {
        return this.numeroCuotasIncentivo;
    }

    public void setNumeroCuotasIncentivo(String numeroCuotasIncentivo) {
        this.numeroCuotasIncentivo = numeroCuotasIncentivo;
    }

    public String getNumeroBonosLiquidados() {
        return this.numeroBonosLiquidados;
    }

    public void setNumeroBonosLiquidados(String numeroBonosLiquidados) {
        this.numeroBonosLiquidados = numeroBonosLiquidados;
    }

    public String getMontoLiquidadoSalud() {
        return this.montoLiquidadoSalud;
    }

    public void setMontoLiquidadoSalud(String montoLiquidadoSalud) {
        this.montoLiquidadoSalud = montoLiquidadoSalud;
    }

    public String getMontoLiquidadoPension() {
        return this.montoLiquidadoPension;
    }

    public void setMontoLiquidadoPension(String montoLiquidadoPension) {
        this.montoLiquidadoPension = montoLiquidadoPension;
    }

    public String getMontoLiquidadoCuota() {
        return this.montoLiquidadoCuota;
    }

    public void setMontoLiquidadoCuota(String montoLiquidadoCuota) {
        this.montoLiquidadoCuota = montoLiquidadoCuota;
    }

    public String getMontoLiquidadoCesantias() {
        return this.montoLiquidadoCesantias;
    }

    public void setMontoLiquidadoCesantias(String montoLiquidadoCesantias) {
        this.montoLiquidadoCesantias = montoLiquidadoCesantias;
    }

    public String getMontoLiquidadoAlimentacion() {
        return this.montoLiquidadoAlimentacion;
    }

    public void setMontoLiquidadoAlimentacion(String montoLiquidadoAlimentacion) {
        this.montoLiquidadoAlimentacion = montoLiquidadoAlimentacion;
    }

    public String getValorTotalPrestaciones() {
        return this.valorTotalPrestaciones;
    }

    public void setValorTotalPrestaciones(String valorTotalPrestaciones) {
        this.valorTotalPrestaciones = valorTotalPrestaciones;
    }

    public String getRenunciaVoluntaria() {
        return this.renunciaVoluntaria;
    }

    public void setRenunciaVoluntaria(String renunciaVoluntaria) {
        this.renunciaVoluntaria = renunciaVoluntaria;
    }

    public Date getFechaRenuncia() {
        return this.fechaRenuncia;
    }

    public void setFechaRenuncia(Date fechaRenuncia) {
        this.fechaRenuncia = fechaRenuncia;
    }

    public String getPerdidaBeneficio() {
        return this.perdidaBeneficio;
    }

    public void setPerdidaBeneficio(String perdidaBeneficio) {
        this.perdidaBeneficio = perdidaBeneficio;
    }

    public Date getFechaPerdidaBeneficio() {
        return this.fechaPerdidaBeneficio;
    }

    public void setFechaPerdidaBeneficio(Date fechaPerdidaBeneficio) {
        this.fechaPerdidaBeneficio = fechaPerdidaBeneficio;
    }

    public String getTerminacionBeneficio() {
        return this.terminacionBeneficio;
    }

    public void setTerminacionBeneficio(String terminacionBeneficio) {
        this.terminacionBeneficio = terminacionBeneficio;
    }

    public Date getFechaTerminacionBeneficio() {
        return this.fechaTerminacionBeneficio;
    }

    public void setFechaTerminacionBeneficio(Date fechaTerminacionBeneficio) {
        this.fechaTerminacionBeneficio = fechaTerminacionBeneficio;
    }

}
