package com.growdata.emprendimiento.persistence.entidadSIMPC;
// Generated 20/06/2019 03:04:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Recobros generated by hbm2java
 */
public class Recobros implements java.io.Serializable {

    private BigDecimal idrecobro;
    private MdFDatosBasicos mdFDatosBasicos;
    private BigDecimal idverificacion;
    private Date fecharegistro;
    private int valorrecobro;
    private Set<Abonos> abonoses = new HashSet<Abonos>(0);

    public Recobros() {
    }

    public Recobros(BigDecimal idrecobro, MdFDatosBasicos mdFDatosBasicos, BigDecimal idverificacion, Date fecharegistro, int valorrecobro) {
        this.idrecobro = idrecobro;
        this.mdFDatosBasicos = mdFDatosBasicos;
        this.idverificacion = idverificacion;
        this.fecharegistro = fecharegistro;
        this.valorrecobro = valorrecobro;
    }

    public Recobros(BigDecimal idrecobro, MdFDatosBasicos mdFDatosBasicos, BigDecimal idverificacion, Date fecharegistro, int valorrecobro, Set<Abonos> abonoses) {
        this.idrecobro = idrecobro;
        this.mdFDatosBasicos = mdFDatosBasicos;
        this.idverificacion = idverificacion;
        this.fecharegistro = fecharegistro;
        this.valorrecobro = valorrecobro;
        this.abonoses = abonoses;
    }

    public BigDecimal getIdrecobro() {
        return this.idrecobro;
    }

    public void setIdrecobro(BigDecimal idrecobro) {
        this.idrecobro = idrecobro;
    }

    public MdFDatosBasicos getMdFDatosBasicos() {
        return this.mdFDatosBasicos;
    }

    public void setMdFDatosBasicos(MdFDatosBasicos mdFDatosBasicos) {
        this.mdFDatosBasicos = mdFDatosBasicos;
    }

    public BigDecimal getIdverificacion() {
        return this.idverificacion;
    }

    public void setIdverificacion(BigDecimal idverificacion) {
        this.idverificacion = idverificacion;
    }

    public Date getFecharegistro() {
        return this.fecharegistro;
    }

    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    public int getValorrecobro() {
        return this.valorrecobro;
    }

    public void setValorrecobro(int valorrecobro) {
        this.valorrecobro = valorrecobro;
    }

    public Set<Abonos> getAbonoses() {
        return this.abonoses;
    }

    public void setAbonoses(Set<Abonos> abonoses) {
        this.abonoses = abonoses;
    }

}
