package com.growdata.emprendimiento.persistence.entidadSIMPC;
// Generated 18/07/2019 02:40:02 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Sedes generated by hbm2java
 */
public class Sedes implements java.io.Serializable {

    private BigDecimal id;
    private Departamentos departamentos;
    private Municipios municipios;
    private String direccion;
    private String codigo;
    private Timestamp fechaCreacion;
    private BigDecimal idUsuarioCreacion;
    private BigDecimal idInstitucion;
    private Timestamp fechaModificacion;
    private BigDecimal idUsuarioModificacion;
    private String nombre;
    private boolean principal;
    private char estado;

    public Sedes() {
    }

    public Sedes(BigDecimal id, Departamentos departamentos, Municipios municipios, String direccion, Timestamp fechaCreacion, BigDecimal idUsuarioCreacion, BigDecimal idInstitucion, String nombre, boolean principal, char estado) {
        this.id = id;
        this.departamentos = departamentos;
        this.municipios = municipios;
        this.direccion = direccion;
        this.fechaCreacion = fechaCreacion;
        this.idUsuarioCreacion = idUsuarioCreacion;
        this.idInstitucion = idInstitucion;
        this.nombre = nombre;
        this.principal = principal;
        this.estado = estado;
    }

    public Sedes(BigDecimal id, Departamentos departamentos, Municipios municipios, String direccion, String codigo, Timestamp fechaCreacion, BigDecimal idUsuarioCreacion, BigDecimal idInstitucion, Timestamp fechaModificacion, BigDecimal idUsuarioModificacion, String nombre, boolean principal, char estado) {
        this.id = id;
        this.departamentos = departamentos;
        this.municipios = municipios;
        this.direccion = direccion;
        this.codigo = codigo;
        this.fechaCreacion = fechaCreacion;
        this.idUsuarioCreacion = idUsuarioCreacion;
        this.idInstitucion = idInstitucion;
        this.fechaModificacion = fechaModificacion;
        this.idUsuarioModificacion = idUsuarioModificacion;
        this.nombre = nombre;
        this.principal = principal;
        this.estado = estado;
    }

    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    public Departamentos getDepartamentos() {
        return this.departamentos;
    }

    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }

    public Municipios getMunicipios() {
        return this.municipios;
    }

    public void setMunicipios(Municipios municipios) {
        this.municipios = municipios;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public Timestamp getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Timestamp fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public BigDecimal getIdUsuarioCreacion() {
        return this.idUsuarioCreacion;
    }

    public void setIdUsuarioCreacion(BigDecimal idUsuarioCreacion) {
        this.idUsuarioCreacion = idUsuarioCreacion;
    }

    public BigDecimal getIdInstitucion() {
        return this.idInstitucion;
    }

    public void setIdInstitucion(BigDecimal idInstitucion) {
        this.idInstitucion = idInstitucion;
    }

    public Timestamp getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Timestamp fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    public BigDecimal getIdUsuarioModificacion() {
        return this.idUsuarioModificacion;
    }

    public void setIdUsuarioModificacion(BigDecimal idUsuarioModificacion) {
        this.idUsuarioModificacion = idUsuarioModificacion;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public boolean isPrincipal() {
        return this.principal;
    }

    public void setPrincipal(boolean principal) {
        this.principal = principal;
    }

    public char getEstado() {
        return this.estado;
    }

    public void setEstado(char estado) {
        this.estado = estado;
    }

}
